### ISSUE TITLE
where's the traffic.avi video?

### ISSUE THREAD

**Issue by ali50mahmoud** [Tes3awy/MatLab-Tutorials#1]
where's the traffic.avi video?

**Comment by SidneyKim** [comment]
Where is the video mentioned in the article??
https://stackoverflow.com/questions/36254452/counting-cars-opencv-python-issue/36274515#36274515

**Comment by Tes3awy** [comment]
@ali50mahmoud @SidneyKim  The video is part of the MATLAB Library, and I cannot upload it as this will be a violation of license. So, if you have MATLAB you'll find it, otherwise you can use any video of your own.
